"""Read and write the per-keystone sidecar file.

The metadata block is TOML rather than YAML so it parses with stdlib `tomllib`
and phase 1 stays dependency-free.
"""

from __future__ import annotations

import re
import tomllib
from pathlib import Path

from keystones.models import Entry

_META_RE = re.compile(r"^```toml\n(.*?)^```\n", re.DOTALL | re.MULTILINE)
_SECTION_RE = re.compile(r"^## (.+?)\n(.*?)(?=^## |\Z)", re.DOTALL | re.MULTILINE)
_CODE_RE = re.compile(r"^```(\w*)\n(.*?)^```", re.DOTALL | re.MULTILINE)


class SidecarError(Exception):
    pass


def parse(path: Path, category: str) -> Entry:
    raw = path.read_text()
    meta_match = _META_RE.search(raw)
    if not meta_match:
        raise SidecarError(f"{path}: no ```toml metadata block")
    meta = tomllib.loads(meta_match.group(1))

    sections = {name.strip().lower(): body for name, body in _SECTION_RE.findall(raw)}
    why = sections.get("why", "").strip()

    source, source_lang = "", "python"
    if "canonical source" in sections:
        code_match = _CODE_RE.search(sections["canonical source"])
        if code_match:
            source_lang = code_match.group(1) or "python"
            source = code_match.group(2).rstrip("\n")

    history = [
        line.strip()[2:].strip()
        for line in sections.get("history", "").splitlines()
        if line.strip().startswith("- ")
    ]

    missing = [k for k in ("target", "hasher", "semantic", "text") if k not in meta]
    if missing:
        raise SidecarError(f"{path}: metadata missing {', '.join(missing)}")

    return Entry(
        id=path.stem,
        category=category,
        target=meta["target"],
        hasher=meta["hasher"],
        semantic=meta["semantic"],
        text=meta["text"],
        review_every=meta.get("review_every"),
        depends=list(meta.get("depends", [])),
        depends_hash=meta.get("depends_hash", ""),
        why=why,
        source=source,
        source_lang=source_lang,
        history=history,
        path=str(path),
    )


def _toml_value(value: object) -> str:
    if isinstance(value, list):
        items = ", ".join(f'"{item}"' for item in value)
        return f"[{items}]"
    return f'"{value}"'


def render(entry: Entry) -> str:
    meta = {
        "target": entry.target,
        "hasher": entry.hasher,
        "semantic": entry.semantic,
        "text": entry.text,
    }
    if entry.review_every:
        meta["review_every"] = entry.review_every
    if entry.depends:
        meta["depends"] = entry.depends
        meta["depends_hash"] = entry.depends_hash

    lines = [f"# {entry.id}", "", "```toml"]
    lines += [f"{key} = {_toml_value(value)}" for key, value in meta.items()]
    lines += ["```", "", "## Why", ""]
    lines.append(entry.why.strip() or "TODO: why is this load-bearing?")
    lines += [
        "",
        "## Canonical source",
        "",
        f"```{entry.source_lang}",
        entry.source,
        "```",
        "",
    ]
    lines += ["## History", ""]
    lines += [f"- {item}" for item in entry.history] or ["- (none)"]
    return "\n".join(lines) + "\n"


def write(path: Path, entry: Entry) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(entry))


def load_all(sidecar_root: Path, categories: tuple[str, ...]) -> list[Entry]:
    entries = []
    for category in categories:
        directory = sidecar_root / category
        if not directory.is_dir():
            continue
        for path in sorted(directory.glob("*.md")):
            entries.append(parse(path, category))
    return entries


def render_index(entries: list[Entry]) -> str:
    lines = ["# Keystones", "", "Generated by `keystones index`. Do not hand-edit.", ""]
    if not entries:
        lines += ["No keystones yet.", ""]
        return "\n".join(lines)
    current = None
    for entry in entries:
        if entry.category != current:
            current = entry.category
            if lines[-1] != "":
                lines.append("")
            lines += [f"## {current}", "", "| id | target | why |", "|---|---|---|"]
        summary = " ".join(entry.why.split())
        if len(summary) > 80:
            summary = summary[:77] + "..."
        lines.append(
            f"| [{entry.id}]({entry.category}/{entry.id}.md) "
            f"| `{entry.target}` | {summary} |"
        )
    lines.append("")
    return "\n".join(lines)
